#!/bin/bash

# List local variables
echo "Local Variables:"
local_vars=$(set -o posix; set)
echo "$local_vars"

# List environment variables
echo -e "\nEnvironment Variables:"
env

# List functions
echo -e "\nFunctions:"
declare -F

